In [1]:
import pandas as pd

url = "https://statiz.sporki.com/stats/?m=total&m2=pitching"
tables = pd.read_html(url)
print(len(tables),"개의 테이블이 있습니다")
df_list = pd.read_html(url)

1 개의 테이블이 있습니다

In [4]:
df=df_list[0]

In [6]:
df

,Rank,Name,Team,정렬▼,G,GS,GR,GF,W,L,...,SO,ROE,BK,WP,ERA,RA9,rRA9,FIP,WHIP,WAR▼
,Rank,Name,Team,WAR,G,GS,GR,GF,W,L,...,SO,ROE,BK,WP,ERA,RA9,rRA9,FIP,WHIP,WAR▼
0,1,선동열,95해P,101.67,367,109,258,308,146,40,...,1698,NaN,8,27,1.20,1.50,1.50,12.45,0.80,101.67
1,2,임창용,18해P,75.31,760,140,620,458,130,86,...,1474,NaN,4,40,3.45,3.81,3.86,63.24,1.18,75.31
2,3,송진우,09빙P,71.42,672,377,295,252,210,153,...,2048,NaN,6,102,3.51,4.02,4.02,85.22,1.29,71.42
3,4,양현종,23+KP,64.70,484,383,101,37,168,113,...,1947,NaN,3,73,3.81,4.16,4.07,66.75,1.37,64.70
4,5,정대현,16SP,63.44,662,0,662,229,46,29,...,559,NaN,0,13,2.21,2.49,2.65,54.89,1.12,63.44
5,6,이강철,05해P,62.61,602,265,337,193,152,112,...,1751,NaN,8,19,3.29,3.63,3.63,62.01,1.16,62.61
6,7,김광현,24+SP,61.88,357,335,22,17,159,88,...,1734,NaN,3,79,3.20,3.64,3.59,55.78,1.31,61.88
7,8,오승환,24+삼P,61.20,670,1,669,581,42,24,...,817,NaN,0,18,2.05,2.21,2.43,35.37,0.94,61.20
8,9,김용수,00MP,61.17,613,129,484,439,126,89,...,1145,NaN,3,27,2.98,3.41,3.41,45.79,1.19,61.17
9,10,김현욱,04삼P,57.69,519,2,517,123,71,31,...,736,NaN,0,6,2.99,3.31,3.31,31.79,1.14,57.69
10,11,정민철,09빙P,50.72,393,370,23,77,161,128,...,1661,NaN,8,55,3.51,3.87,3.87,62.40,1.19,50.72
11,12,조웅천,09태P,48.64,813,13,800,313,64,54,...,920,NaN,1,15,3.21,3.62,3.62,67.08,1.20,48.64
12,13,한용덕,04빙P,48.44,482,259,223,145,120,118,...,1344,NaN,6,46,3.54,3.96,3.96,65.90,1.17,48.44
13,14,구대성,10빙P,47.98,569,43,526,376,67,71,...,1221,NaN,3,35,2.85,3.29,3.29,41.84,1.13,47.98
14,15,윤성환,20삼P,45.43,425,305,120,34,135,106,...,1357,NaN,1,45,4.23,4.57,4.48,65.02,1.32,45.43
15,16,조규제,05쌍P,45.19,508,37,471,283,54,64,...,838,NaN,5,37,3.07,3.31,3.31,83.21,1.18,45.19
16,17,조계현,01해P,45.00,320,260,60,109,126,92,...,1100,NaN,4,34,3.17,3.63,3.63,49.71,1.19,45.00
17,18,정명원,00태P,44.40,395,82,313,289,75,54,...,634,NaN,6,44,2.57,3.21,3.21,39.99,1.15,44.40
18,19,정우람,23+SP,43.71,1004,0,1004,440,64,47,...,937,NaN,2,35,3.18,3.42,3.60,65.55,1.20,43.71
19,20,손민한,15롯P,42.34,388,260,128,73,123,88,...,968,NaN,1,48,3.55,3.90,3.90,63.67,1.27,42.34
20,21,진필중,06OP,40.61,510,86,424,363,75,70,...,751,NaN,3,51,3.20,3.69,3.69,42.36,1.29,40.61
21,22,김시진,92삼P,39.52,273,205,68,115,124,73,...,931,NaN,3,41,3.12,3.54,3.54,42.21,1.30,39.52
22,23,이상훈,04LP,38.45,308,84,224,203,71,40,...,781,NaN,7,14,2.56,2.84,2.84,22.92,1.05,38.45
23,24,윤학길,97롯P,38.17,308,231,77,155,117,94,...,916,NaN,2,37,3.33,3.77,3.77,48.19,1.25,38.17
24,25,최동원,90롯P,38.08,248,124,124,185,103,74,...,1019,NaN,2,20,2.46,3.04,3.04,21.53,1.15,38.08
25,26,류현진,24+한P,37.98,191,182,9,31,98,53,...,1238,NaN,3,36,2.81,3.08,3.08,19.97,1.16,37.98
26,27,정민태,08태P,37.12,290,270,20,56,124,96,...,1278,NaN,2,55,3.48,4.00,4.00,64.66,1.24,37.12
27,28,위재영,06태P,37.05,350,135,215,126,68,64,...,856,NaN,6,23,3.27,3.72,3.72,47.29,1.31,37.05
28,29,장원준,23롯P,36.72,446,341,105,27,132,119,...,1385,NaN,2,60,4.28,4.72,4.66,92.73,1.46,36.72
29,30,정재훈,16두P,36.68,555,19,536,271,35,44,...,677,NaN,1,18,3.14,3.57,3.61,56.40,1.24,36.68
30,31,성준,99삼P,35.99,301,216,85,63,97,66,...,575,NaN,4,22,3.32,3.72,3.72,60.50,1.34,35.99
31,32,우규민,24+LP,35.34,760,130,630,228,82,86,...,866,NaN,2,15,3.95,4.52,4.43,75.38,1.32,35.34
32,33,리오스,07KP,34.71,215,173,42,57,90,59,...,807,NaN,1,30,3.01,3.41,3.41,22.04,1.19,34.71
33,34,니퍼트,18두P,34.63,214,205,9,9,102,51,...,1082,NaN,0,60,3.59,3.88,3.83,32.34,1.28,34.63
34,35,염종석,08롯P,34.42,356,291,65,64,93,133,...,1016,NaN,4,56,3.76,4.25,4.25,60.29,1.28,34.42
35,36,윤석민,18KP,33.44,398,144,254,178,77,75,...,1072,NaN,4,29,3.29,3.66,3.73,42.90,1.22,33.44
36,37,박충식,02삼P,32.90,241,115,126,106,77,44,...,601,NaN,7,8,3.07,3.49,3.49,30.05,1.05,32.90
37,38,권혁,20삼P,32.64,781,14,767,156,58,47,...,762,NaN,5,38,3.79,4.16,4.21,79.79,1.34,32.64
38,39,배영수,19삼P,32.36,499,358,141,58,138,122,...,1436,NaN,13,98,4.46,4.92,4.85,81.90,1.43,32.36
39,40,송승준,20롯P,32.02,338,280,58,20,109,85,...,1238,NaN,1,76,4.49,4.88,4.81,63.71,1.44,32.02
40,41,김정수,03해P,31.93,600,185,415,123,92,77,...,1131,NaN,5,43,3.28,3.83,3.83,64.79,1.27,31.93
41,42,이상군,01빙P,31.71,320,168,152,155,100,77,...,622,NaN,3,41,3.24,3.76,3.76,60.43,1.24,31.71
42,43,장원삼,20현P,31.59,367,287,80,16,121,98,...,1201,NaN,2,40,4.28,4.67,4.61,71.30,1.37,31.59
43,44,김원형,10쌍P,31.27,545,317,228,125,134,144,...,1246,NaN,5,67,3.92,4.54,4.54,86.52,1.35,31.27
44,45,김상진,03OP,31.16,359,267,92,99,122,100,...,1237,NaN,2,51,3.54,4.10,4.10,49.28,1.26,31.16
45,46,주형광,07롯P,30.94,386,217,169,61,87,82,...,1209,NaN,1,27,3.83,4.20,4.20,67.47,1.23,30.94
46,47,권영호,89삼P,30.50,288,86,202,175,56,49,...,422,NaN,6,15,3.06,3.42,3.42,29.32,1.25,30.50
47,48,안지만,16삼P,29.98,593,28,565,117,60,35,...,773,NaN,0,35,3.59,3.85,4.04,59.71,1.27,29.98
48,49,소사,19KP,29.52,210,206,4,11,77,63,...,1059,NaN,4,40,4.28,4.69,4.56,31.23,1.32,29.52
49,50,박명환,15OP,29.48,326,260,66,46,103,93,...,1421,NaN,3,119,3.81,4.17,4.18,72.54,1.35,29.48

In [11]:
# 두 번째 레벨의 컬럼명만 선택하여 사용
df.columns = df.columns.get_level_values(0)

In [12]:
df

,Rank,Name,Team,WAR,G,GS,GR,GF,W,L,...,SO,ROE,BK,WP,ERA,RA9,rRA9,FIP,WHIP,WAR▼
0,1,선동열,95해P,101.67,367,109,258,308,146,40,...,1698,NaN,8,27,1.20,1.50,1.50,12.45,0.80,101.67
1,2,임창용,18해P,75.31,760,140,620,458,130,86,...,1474,NaN,4,40,3.45,3.81,3.86,63.24,1.18,75.31
2,3,송진우,09빙P,71.42,672,377,295,252,210,153,...,2048,NaN,6,102,3.51,4.02,4.02,85.22,1.29,71.42
3,4,양현종,23+KP,64.70,484,383,101,37,168,113,...,1947,NaN,3,73,3.81,4.16,4.07,66.75,1.37,64.70
4,5,정대현,16SP,63.44,662,0,662,229,46,29,...,559,NaN,0,13,2.21,2.49,2.65,54.89,1.12,63.44
5,6,이강철,05해P,62.61,602,265,337,193,152,112,...,1751,NaN,8,19,3.29,3.63,3.63,62.01,1.16,62.61
6,7,김광현,24+SP,61.88,357,335,22,17,159,88,...,1734,NaN,3,79,3.20,3.64,3.59,55.78,1.31,61.88
7,8,오승환,24+삼P,61.20,670,1,669,581,42,24,...,817,NaN,0,18,2.05,2.21,2.43,35.37,0.94,61.20
8,9,김용수,00MP,61.17,613,129,484,439,126,89,...,1145,NaN,3,27,2.98,3.41,3.41,45.79,1.19,61.17
9,10,김현욱,04삼P,57.69,519,2,517,123,71,31,...,736,NaN,0,6,2.99,3.31,3.31,31.79,1.14,57.69
10,11,정민철,09빙P,50.72,393,370,23,77,161,128,...,1661,NaN,8,55,3.51,3.87,3.87,62.40,1.19,50.72
11,12,조웅천,09태P,48.64,813,13,800,313,64,54,...,920,NaN,1,15,3.21,3.62,3.62,67.08,1.20,48.64
12,13,한용덕,04빙P,48.44,482,259,223,145,120,118,...,1344,NaN,6,46,3.54,3.96,3.96,65.90,1.17,48.44
13,14,구대성,10빙P,47.98,569,43,526,376,67,71,...,1221,NaN,3,35,2.85,3.29,3.29,41.84,1.13,47.98
14,15,윤성환,20삼P,45.43,425,305,120,34,135,106,...,1357,NaN,1,45,4.23,4.57,4.48,65.02,1.32,45.43
15,16,조규제,05쌍P,45.19,508,37,471,283,54,64,...,838,NaN,5,37,3.07,3.31,3.31,83.21,1.18,45.19
16,17,조계현,01해P,45.00,320,260,60,109,126,92,...,1100,NaN,4,34,3.17,3.63,3.63,49.71,1.19,45.00
17,18,정명원,00태P,44.40,395,82,313,289,75,54,...,634,NaN,6,44,2.57,3.21,3.21,39.99,1.15,44.40
18,19,정우람,23+SP,43.71,1004,0,1004,440,64,47,...,937,NaN,2,35,3.18,3.42,3.60,65.55,1.20,43.71
19,20,손민한,15롯P,42.34,388,260,128,73,123,88,...,968,NaN,1,48,3.55,3.90,3.90,63.67,1.27,42.34
20,21,진필중,06OP,40.61,510,86,424,363,75,70,...,751,NaN,3,51,3.20,3.69,3.69,42.36,1.29,40.61
21,22,김시진,92삼P,39.52,273,205,68,115,124,73,...,931,NaN,3,41,3.12,3.54,3.54,42.21,1.30,39.52
22,23,이상훈,04LP,38.45,308,84,224,203,71,40,...,781,NaN,7,14,2.56,2.84,2.84,22.92,1.05,38.45
23,24,윤학길,97롯P,38.17,308,231,77,155,117,94,...,916,NaN,2,37,3.33,3.77,3.77,48.19,1.25,38.17
24,25,최동원,90롯P,38.08,248,124,124,185,103,74,...,1019,NaN,2,20,2.46,3.04,3.04,21.53,1.15,38.08
25,26,류현진,24+한P,37.98,191,182,9,31,98,53,...,1238,NaN,3,36,2.81,3.08,3.08,19.97,1.16,37.98
26,27,정민태,08태P,37.12,290,270,20,56,124,96,...,1278,NaN,2,55,3.48,4.00,4.00,64.66,1.24,37.12
27,28,위재영,06태P,37.05,350,135,215,126,68,64,...,856,NaN,6,23,3.27,3.72,3.72,47.29,1.31,37.05
28,29,장원준,23롯P,36.72,446,341,105,27,132,119,...,1385,NaN,2,60,4.28,4.72,4.66,92.73,1.46,36.72
29,30,정재훈,16두P,36.68,555,19,536,271,35,44,...,677,NaN,1,18,3.14,3.57,3.61,56.40,1.24,36.68
30,31,성준,99삼P,35.99,301,216,85,63,97,66,...,575,NaN,4,22,3.32,3.72,3.72,60.50,1.34,35.99
31,32,우규민,24+LP,35.34,760,130,630,228,82,86,...,866,NaN,2,15,3.95,4.52,4.43,75.38,1.32,35.34
32,33,리오스,07KP,34.71,215,173,42,57,90,59,...,807,NaN,1,30,3.01,3.41,3.41,22.04,1.19,34.71
33,34,니퍼트,18두P,34.63,214,205,9,9,102,51,...,1082,NaN,0,60,3.59,3.88,3.83,32.34,1.28,34.63
34,35,염종석,08롯P,34.42,356,291,65,64,93,133,...,1016,NaN,4,56,3.76,4.25,4.25,60.29,1.28,34.42
35,36,윤석민,18KP,33.44,398,144,254,178,77,75,...,1072,NaN,4,29,3.29,3.66,3.73,42.90,1.22,33.44
36,37,박충식,02삼P,32.90,241,115,126,106,77,44,...,601,NaN,7,8,3.07,3.49,3.49,30.05,1.05,32.90
37,38,권혁,20삼P,32.64,781,14,767,156,58,47,...,762,NaN,5,38,3.79,4.16,4.21,79.79,1.34,32.64
38,39,배영수,19삼P,32.36,499,358,141,58,138,122,...,1436,NaN,13,98,4.46,4.92,4.85,81.90,1.43,32.36
39,40,송승준,20롯P,32.02,338,280,58,20,109,85,...,1238,NaN,1,76,4.49,4.88,4.81,63.71,1.44,32.02
40,41,김정수,03해P,31.93,600,185,415,123,92,77,...,1131,NaN,5,43,3.28,3.83,3.83,64.79,1.27,31.93
41,42,이상군,01빙P,31.71,320,168,152,155,100,77,...,622,NaN,3,41,3.24,3.76,3.76,60.43,1.24,31.71
42,43,장원삼,20현P,31.59,367,287,80,16,121,98,...,1201,NaN,2,40,4.28,4.67,4.61,71.30,1.37,31.59
43,44,김원형,10쌍P,31.27,545,317,228,125,134,144,...,1246,NaN,5,67,3.92,4.54,4.54,86.52,1.35,31.27
44,45,김상진,03OP,31.16,359,267,92,99,122,100,...,1237,NaN,2,51,3.54,4.10,4.10,49.28,1.26,31.16
45,46,주형광,07롯P,30.94,386,217,169,61,87,82,...,1209,NaN,1,27,3.83,4.20,4.20,67.47,1.23,30.94
46,47,권영호,89삼P,30.50,288,86,202,175,56,49,...,422,NaN,6,15,3.06,3.42,3.42,29.32,1.25,30.50
47,48,안지만,16삼P,29.98,593,28,565,117,60,35,...,773,NaN,0,35,3.59,3.85,4.04,59.71,1.27,29.98
48,49,소사,19KP,29.52,210,206,4,11,77,63,...,1059,NaN,4,40,4.28,4.69,4.56,31.23,1.32,29.52
49,50,박명환,15OP,29.48,326,260,66,46,103,93,...,1421,NaN,3,119,3.81,4.17,4.18,72.54,1.35,29.48

In [14]:
columns_to_drop = ['Rank', '2B', '3B','ROE','WAR▼']
df = df.drop(columns=columns_to_drop)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    50 non-null     object
 1   Team    50 non-null     object
 2   WAR     50 non-null     float64
 3   G       50 non-null     int64
 4   GS      50 non-null     int64
 5   GR      50 non-null     int64
 6   GF      50 non-null     int64
 7   W       50 non-null     int64
 8   L       50 non-null     int64
 9   S       50 non-null     int64
 10  HD      50 non-null     int64
 11  IP      50 non-null     float64
 12  ER      50 non-null     int64
 13  R       50 non-null     int64
 14  rRA     50 non-null     float64
 15  TBF     50 non-null     int64
 16  H       50 non-null     int64
 17  HR      50 non-null     int64
 18  BB      50 non-null     int64
 19  HP      50 non-null     int64
 20  IB      50 non-null     int64
 21  SO      50 non-null     int64
 22  BK      50 non-null     int64
 23  WP      50 non-null     int64
 24  ERA     50 non-null     float64
 25  RA9     50 non-null     float64
 26  rRA9    50 non-null     float64
 27  FIP     50 non-null     float64
 28  WHIP    50 non-null     float64
dtypes: float64(8), int64(19), object(2)
memory usage: 11.5+ KB

In [49]:
df.head(30)

,Name,Team,WAR,G,GS,GR,GF,W,L,S,...,HP,IB,SO,BK,WP,ERA,RA9,rRA9,FIP,WHIP
0,선동열,95해P,101.67,367,109,258,308,146,40,132,...,62,14,1698,8,27,1.20,1.50,1.50,12.45,0.80
1,임창용,18해P,75.31,760,140,620,458,130,86,258,...,152,44,1474,4,40,3.45,3.81,3.86,63.24,1.18
2,송진우,09빙P,71.42,672,377,295,252,210,153,103,...,117,55,2048,6,102,3.51,4.02,4.02,85.22,1.29
3,양현종,23+KP,64.70,484,383,101,37,168,113,0,...,51,6,1947,3,73,3.81,4.16,4.07,66.75,1.37
4,정대현,16SP,63.44,662,0,662,229,46,29,106,...,49,57,559,0,13,2.21,2.49,2.65,54.89,1.12
5,이강철,05해P,62.61,602,265,337,193,152,112,53,...,189,56,1751,8,19,3.29,3.63,3.63,62.01,1.16
6,김광현,24+SP,61.88,357,335,22,17,159,88,0,...,46,13,1734,3,79,3.20,3.64,3.59,55.78,1.31
7,오승환,24+삼P,61.20,670,1,669,581,42,24,401,...,16,15,817,0,18,2.05,2.21,2.43,35.37,0.94
8,김용수,00MP,61.17,613,129,484,439,126,89,227,...,61,55,1145,3,27,2.98,3.41,3.41,45.79,1.19
9,김현욱,04삼P,57.69,519,2,517,123,71,31,22,...,59,25,736,0,6,2.99,3.31,3.31,31.79,1.14
10,정민철,09빙P,50.72,393,370,23,77,161,128,10,...,93,24,1661,8,55,3.51,3.87,3.87,62.40,1.19
11,조웅천,09태P,48.64,813,13,800,313,64,54,98,...,65,55,920,1,15,3.21,3.62,3.62,67.08,1.20
12,한용덕,04빙P,48.44,482,259,223,145,120,118,24,...,119,46,1344,6,46,3.54,3.96,3.96,65.90,1.17
13,구대성,10빙P,47.98,569,43,526,376,67,71,214,...,57,48,1221,3,35,2.85,3.29,3.29,41.84,1.13
14,윤성환,20삼P,45.43,425,305,120,34,135,106,1,...,102,3,1357,1,45,4.23,4.57,4.48,65.02,1.32
15,조규제,05쌍P,45.19,508,37,471,283,54,64,153,...,46,35,838,5,37,3.07,3.31,3.31,83.21,1.18
16,조계현,01해P,45.00,320,260,60,109,126,92,17,...,79,13,1100,4,34,3.17,3.63,3.63,49.71,1.19
17,정명원,00태P,44.40,395,82,313,289,75,54,142,...,35,41,634,6,44,2.57,3.21,3.21,39.99,1.15
18,정우람,23+SP,43.71,1004,0,1004,440,64,47,197,...,45,37,937,2,35,3.18,3.42,3.60,65.55,1.20
19,손민한,15롯P,42.34,388,260,128,73,123,88,22,...,52,26,968,1,48,3.55,3.90,3.90,63.67,1.27
20,진필중,06OP,40.61,510,86,424,363,75,70,191,...,42,34,751,3,51,3.20,3.69,3.69,42.36,1.29
21,김시진,92삼P,39.52,273,205,68,115,124,73,16,...,83,21,931,3,41,3.12,3.54,3.54,42.21,1.30
22,이상훈,04LP,38.45,308,84,224,203,71,40,98,...,23,26,781,7,14,2.56,2.84,2.84,22.92,1.05
23,윤학길,97롯P,38.17,308,231,77,155,117,94,10,...,41,20,916,2,37,3.33,3.77,3.77,48.19,1.25
24,최동원,90롯P,38.08,248,124,124,185,103,74,26,...,47,15,1019,2,20,2.46,3.04,3.04,21.53,1.15
25,류현진,24+한P,37.98,191,182,9,31,98,53,1,...,23,20,1238,3,36,2.81,3.08,3.08,19.97,1.16
26,정민태,08태P,37.12,290,270,20,56,124,96,3,...,39,17,1278,2,55,3.48,4.00,4.00,64.66,1.24
27,위재영,06태P,37.05,350,135,215,126,68,64,71,...,27,19,856,6,23,3.27,3.72,3.72,47.29,1.31
28,장원준,23롯P,36.72,446,341,105,27,132,119,1,...,112,27,1385,2,60,4.28,4.72,4.66,92.73,1.46
29,정재훈,16두P,36.68,555,19,536,271,35,44,139,...,51,29,677,1,18,3.14,3.57,3.61,56.40,1.24

In [45]:
url = "https://statiz.sporki.com/player/?m=year&p_no=13934"
tables = pd.read_html(url)
print(len(tables),"개의 테이블이 있습니다")
df_list = pd.read_html(url)
df_list[0]

1 개의 테이블이 있습니다

,Year,Team,Age,Pos.,G,GS,GR,GF,W,L,...,SO,ROE,BK,WP,ERA,RA9,rRA9,FIP,WHIP,WAR
,Year,Team,Age,Pos.,G,GS,GR,GF,W,L,...,SO,ROE,BK,WP,ERA,RA9,rRA9,FIP,WHIP,WAR
,Year,Total,Total,Pos.,G,GS,GR,GF,W,L,...,SO,ROE,BK,WP,ERA,RA9,rRA9,FIP,WHIP,WAR
,Year,Total,Total,Pos.,G,GS,GR,GF,W,L,...,SO,ROE,BK,WP,ERA,RA9,rRA9,FIP,WHIP,WAR
0,2019,LG,30,P,29,29,0,0,14,12,...,126,8,0,12,2.55,3.49,3.49,3.50,1.14,4.03
1,2020,LG,31,P,28,28,0,1,15,7,...,134,5,0,4,3.32,3.48,3.48,4.07,1.15,5.57
2,2021,LG,32,P,30,30,0,0,13,8,...,142,7,1,7,3.15,3.25,3.21,3.76,1.24,5.63
3,2022,LG,33,P,27,27,0,0,16,4,...,153,5,0,3,2.54,2.71,2.71,2.89,1.08,5.26
4,2023,LG,34,P,30,30,0,0,10,7,...,129,7,0,6,3.83,4.38,4.13,3.49,1.24,3.41
5,5시즌,통산,통산,P,144,144,0,1,68,38,...,684,32,1,32,3.08,3.47,3.41,17.72,1.17,23.90

In [46]:
df2=df_list[0]

In [47]:
# 두 번째 레벨의 컬럼명만 선택하여 사용
df2.columns = df2.columns.get_level_values(1)

In [48]:
df2

,Year,Team,Age,Pos.,G,GS,GR,GF,W,L,...,SO,ROE,BK,WP,ERA,RA9,rRA9,FIP,WHIP,WAR
0,2019,LG,30,P,29,29,0,0,14,12,...,126,8,0,12,2.55,3.49,3.49,3.50,1.14,4.03
1,2020,LG,31,P,28,28,0,1,15,7,...,134,5,0,4,3.32,3.48,3.48,4.07,1.15,5.57
2,2021,LG,32,P,30,30,0,0,13,8,...,142,7,1,7,3.15,3.25,3.21,3.76,1.24,5.63
3,2022,LG,33,P,27,27,0,0,16,4,...,153,5,0,3,2.54,2.71,2.71,2.89,1.08,5.26
4,2023,LG,34,P,30,30,0,0,10,7,...,129,7,0,6,3.83,4.38,4.13,3.49,1.24,3.41
5,5시즌,통산,통산,P,144,144,0,1,68,38,...,684,32,1,32,3.08,3.47,3.41,17.72,1.17,23.90